### ISSUE TITLE
Välj plattform och programmeringsspråk

### ISSUE THREAD

**Issue by mikaelsvensson** [devscoutsweden/scoutapi#3]
Utred vilka plattformar, verktyg, ramverk och programmeringsspråk som är relevanta och som vi har kompetens inom. Välj vilka som ska användas.

**Comment by frozzare** [comment]
Förslag: Ruby, när vi valt programmeringsspråk tycker jag vi följer en stilguide, t ex https://github.com/bbatsov/ruby-style-guide om vi nu väljer Ruby, så blir koden trevligare och finare att läsa!

**Comment by mikaelsvensson** [comment]
Jag kan inget om Ruby men eftersom inga andra förslag kommit in så tycker jag vi kör på Ruby eftersom i alla fall frozzare vet hur det fungerar.

**Comment by mikaelsvensson** [comment]
Programmeringsspråk och ramverk: Ruby och Rails.
Databas: PostgreSQL (eventuellt minnesdatabas eller SQLite i test- och utvecklingsmiljöer).
Test- och produktionsmiljö: Inledningsvis ska Heroku användas.
