### ISSUE TITLE
Category images

### ISSUE THREAD

**Issue by TheSwedishScout** [devscoutsweden/scoutapi#31]
In the categories "Hantverk, pyssel" (id 7) and "Friluftsliv sjö" (id 13) the media tag is missing. In the app the category  "Frilufsliv sjö" has no image butthaer is an category called "Friufsliv på vatten" witch is empty.

**Comment by mikaelsvensson** [comment]
Categories 7 and 13 have not been assigned images, so the API returns the correct information. I have assigned the same image for category 13 as for category "Friluftsliv på vatten".

**Comment by mikaelsvensson** [comment]
I guess the reporter does not want empty categories to be shown. Correct?

I suggest that a "usage counter" is added to the result when listing categories. This counter should show, for each category, how many activities have been assigned to the category.

Clients, such as the Android app, can then choose whether or not to display a category based on this counter (i.e. the number of activities assigned to the category).

**Comment by mikaelsvensson** [comment]
The Android app does not seem to notice the new image for category 13. We may need to report this as a bug on https://github.com/devscoutsweden/aktivitetsbanken-android/issues.

**Comment by mikaelsvensson** [comment]
The image of the handicraft category has been set to http://www.mikaelsvensson.info/scoutapi/media/category_upplgg_hantverk_pyssel.png.

**Comment by mikaelsvensson** [comment]
Have fixed API but the Android app will not notice until its next release.
