### ISSUE TITLE
Sorting - labels are moving but not the object 

### ISSUE THREAD

**Issue by TheSwedishScout** [devscoutsweden/scoutapi#37]
When sorting in any other way then default just the lable change but not the link so you don't get the one you think you get the one that was thare in the default sorting

**Comment by mikaelsvensson** [comment]
Does not appear to be an API issue but instead an app issue. Closing this issue and creating new app issue instead. See https://github.com/devscoutsweden/aktivitetsbanken-android/issues/101.
