### ISSUE TITLE
API for related activities

### ISSUE THREAD

**Issue by mikaelsvensson** [devscoutsweden/scoutapi#40]
Add support for linking one activity to another, i.e. make it possible for clients to show a list of similar/related activities when displaying a particular activity.

The API should be able to differentiate between relations created by "some robot" and relations created by humans. The functional difference is that "robot relations" (i.e. auto-generated relations) may be deleted at any time. More specifically, setting auto-generated relations for an activity deletes all pre-existing relations for that activity before adding the new ones.

When GETting an activity: List of related activity ids is returned. Titles, or other pieces of information, for the related activites should not be returned by the API (in order to conserve bandwidth for mobile users).

**Comment by TheSwedishScout** [comment]
would it be possible to have something similar with static id, for activity series or assign in this some that are always there?

**Comment by mikaelsvensson** [comment]
On 2015-04-14 23:24, TheSwedishScout wrote:

> would it be possible to have something similar with static id, for 
> activity series or assign in this some that are always there?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/devscoutsweden/scoutapi/issues/40#issuecomment-93067591.
> 
> At the moment, I would suggest using categories for this functionality 
> since a category can be thought of as a named list of activities. 
> Categories are (fortunately?) global and public.

Creating an activity serie using categories would (probably) entain 
these steps:
1. Create the activity. I would recommend setting the category's group 
to the user's id or name.
2. Update each activity belonging to this serie/category. I would 
recommend first GETting the activity, modifying the response to add the 
new category's id and then PUTting the modified response to update the 
activity with the additional category.

Docs:
https://github.com/devscoutsweden/scoutapi/blob/dev/README.API.rdoc#create-new-category
https://github.com/devscoutsweden/scoutapi/blob/dev/README.API.Activities.rdoc#readshow-activity
https://github.com/devscoutsweden/scoutapi/blob/dev/README.API.Activities.rdoc#update-activity

Note: "Proper" activity series support has been discussed but other 
features have been considered more important.
