### ISSUE TITLE
Max content length is shorter than the longest activity in Aktivitetsbanken 

### ISSUE THREAD

**Issue by zegl** [devscoutsweden/scoutapi#45]
http://www.scouterna.se/aktiviteter-och-lager/aktivitetsbanken/aktivitet/wild-scouts-reflektion/

The description content of "Wild Scouts Reflektion" is 14102 characters long after parsing and converting to markdown. Our max length is currently 10000 characters, and would need to be increased.

**Comment by mikaelsvensson** [comment]
Column sizes increased to 50KB.
