### ISSUE TITLE
Långsamt API

### ISSUE THREAD

**Issue by zegl** [devscoutsweden/scoutapi#9]
Efter att ha kört crawlen (#7) och skickat 922 av 967 aktiviteter till backenden så blir allt otroligt långsamt. 

Att hämta `GET http://infinite-forest-4832.herokuapp.com/api/v1/activities` tar nästan 20 sekunder, vilket inte är optimalt.

Alla operationer borde ta max 1s. Det här kanske enkelt går att fixa genom att hosta själva istället för på Heroku?

**Comment by mikaelsvensson** [comment]
När jag testade nyss så tog det 15 sekunder att få upp resultatet första gången. Därefter tog det 2-3 sekunder per försök. När jag tittade i serverloggen som förklarades det långsamma första anropet med att applikationen var tvungen att först startas upp, eftersom Heroku-plattformen tidigare stängt ner den pga. inaktivitet (vilket verkar ske om inga anrop gjorts senaste timmen).

**Comment by zegl** [comment]
Det visade sig att jag kan ha gjort lite för många onödiga uppslag. Stänger denna.
